# Title of your blog; shows in the header
name: "Ripple"

# Description of your content (will only be used on Google Search)
description: "Hey, I'm Stefan and this is my blog. I write about making games, writing code, and whatever else."

# Your name. Will show in your footer + sidebar
author: "Stefan Valentin"

url: ""
baseurl: ""
homeurl: "index.html"

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Writer of code. Drinker of white russians. Dreams of owning a naked mole rat farm."
site-description: "This is the development blog for the game I'm working on called Ripple. It's a 2D turn based simulation/strategy game that draws inspiration from Majesty, Dwarf Fortress, and the Sims."
site-description-2: "For a more detailed description of my vision for the game check out <a href='/development/lets-call-it-ripple/'>this blog post</a>."
site-description-3: "You can also take a look at what I'm actively working on development-wise by going to my <a href='https://trello.com/b/nflkl8Nn/ripple'>Trello board.</a>"
subscribe-link: "If you want to stay updated on the game's progress <a href='/subscribe/'>subscribe to the mailing list.</a>"
about-part-1: "Ripple is a fantasy town simulator that draws inspiration from Majesty, Dwarf Fortress, and the Sims. The goal of the game is to start with a group of unskilled settlers and try to build a thriving community in a harsh unforgiving environment."
about-part-2: "The game also aims to include interesting random characters who wander the world and may visit your town, either offering aid or posing challenges for your settlement."
about-part-3: "And finally each citizen in your town will lead an interesting life, with characteristics, skills, and interests that develop over time to set them apart from their fellow townspeople."

# Social Accounts (mine, as placeholders)

twitter: slowestbro
github: trash

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: auto
ga_tracking_id: UA-51746110-1
google_analytics:   UA-51746110-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
highlighter: rouge

paginate: 10
paginate_path: "/posts/:num"

future: true

# SCSS

sass:
  sass_dir: _scss
  style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

gems: [jekyll-paginate]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

exclude: ['node_modules']